# Site settings
title: IV122
description: Overview of work done in course IV122 Mathematics and Programming.
baseurl: "/iv122"
url: "http://ondrejslamecka.github.com/iv122"

# Build settings
markdown: kramdown
